// Hand-drawn 8-bit sprites. Every sprite faces RIGHT; the renderer flips or
// rotates quads for the other directions. '.' is transparent.
// Rows must all be the same width — dev/check.mjs enforces it.

export const PAL = {
    k: '#000000', w: '#ffffff', W: '#c8c8dc', g: '#8a8aa0', G: '#484858',
    r: '#e83820', R: '#ff9070', d: '#8c1808',
    y: '#ffd820', Y: '#fff4a8', o: '#ff8c10', O: '#9c4a10', u: '#5c3010',
    b: '#2850ff', B: '#90b4ff', n: '#141c80',
    c: '#10e8ff', C: '#c0ffff', t: '#0888a8',
    e: '#18b030', E: '#90f050', f: '#0a5818',
    p: '#a038e8', P: '#e8a0ff', q: '#501878',
    m: '#ff40a8', s: '#ffc890', S: '#c88050',
};

const E16 = '................';

export const SPRITES = {
    // ---------------------------------------------------------- the miner
    player0: [
        E16,
        '....yyyyyyy.....',
        '...yyYyyyyyyy...',
        '...yyyyyyyyyWw..',
        '..OOOOOOOOOOOO..',
        '....ssssssks....',
        '....sssssssss...',
        '.....Ssssss.....',
        '...bbbbbbbbb....',
        '..bBbbbbbbbbsgg.',
        '..bBbbbbbbbb.ggg',
        '..bbbbbbbbbb....',
        '...bbbbbbbbb....',
        '....bbbbbbb.....',
        '...uuuu.uuuu....',
        E16,
    ],
    player1: [
        E16,
        '....yyyyyyy.....',
        '...yyYyyyyyyy...',
        '...yyyyyyyyyWw..',
        '..OOOOOOOOOOOO..',
        '....ssssssks....',
        '....sssssssss...',
        '.....Ssssss.....',
        '...bbbbbbbbb....',
        '..bBbbbbbbbbsgg.',
        '..bBbbbbbbbb.ggg',
        '..bbbbbbbbbb....',
        '...bbbbbbbbb....',
        '..bbb.....bbb...',
        '.uuuu......uuuu.',
        E16,
    ],

    // ---------------------------------------------------------- enemies
    grub0: [
        E16,
        '.....rrrrrr.....',
        '...rrRRrrrrrr...',
        '..rRRrrrrrrrrr..',
        '..rRrrrrrrrrrrr.',
        '.rrWWWWrrrWWWWr.',
        '.rWykkWrrrWykkW.',
        '.rWyykWrrrWyykW.',
        '.rrWWWWrrrWWWWrr',
        '.rrrrrrrrrrrrrrr',
        '.rrrrrwwwwwrrrr.',
        '..rrrrrrrrrrrrr.',
        '..drrrrrrrrrrrd.',
        '...dddrrrrrddd..',
        '...kkk....kkk...',
        '..kkkk....kkkk..',
    ],
    grub1: [
        E16,
        '.....rrrrrr.....',
        '...rrRRrrrrrr...',
        '..rRRrrrrrrrrr..',
        '..rRrrrrrrrrrrr.',
        '.rrWWWWrrrWWWWr.',
        '.rWykkWrrrWykkW.',
        '.rWyykWrrrWyykW.',
        '.rrWWWWrrrWWWWrr',
        '.rrrrrrrrrrrrrrr',
        '.rrrrrwwwwwrrrr.',
        '..rrrrrrrrrrrrr.',
        '..drrrrrrrrrrrd.',
        '...dddrrrrrddd..',
        '....kkk..kkk....',
        '...kkk....kkk...',
    ],
    drake0: [
        E16,
        '...........eee..',
        '..........eEeeee',
        '..e.e....eekeeee',
        '..eeeee..eeeeeee',
        '...eeeeeeeeerrr.',
        '..eeeeeeeeeee...',
        '.eeeyyyyyeee....',
        '.eeyyyyyyee.....',
        'eeeyyyyyyee.....',
        'ee.eeeeeeee.....',
        'e...fee..fee....',
        '....ffe..ffe....',
        '...fff..fff.....',
        E16,
        E16,
    ],
    drake1: [
        E16,
        '...........eee..',
        '..........eEeeee',
        '..e.e....eekeeee',
        '..eeeee..eeeeeee',
        '...eeeeeeeeerrr.',
        '..eeeeeeeeeee...',
        '.eeeyyyyyeee....',
        '.eeyyyyyyee.....',
        'eeeyyyyyyee.....',
        'ee.eeeeeeee.....',
        'e...fee...fee...',
        '...ffe....ffe...',
        '..fff....fff....',
        E16,
        E16,
    ],
    skitter0: [
        E16,
        E16,
        '...........k.k..',
        '............kk..',
        '.....ppppp.PPP..',
        '...ppPPpppppPwP.',
        '..pPPpppppppPPP.',
        '..pPppppqppppp..',
        '..ppppppqpppp...',
        '...pppppqppp....',
        '....qqqqqqq.....',
        '...k..k..k......',
        '..k..k..k.......',
        E16,
        E16,
        E16,
    ],
    skitter1: [
        E16,
        E16,
        '...........k.k..',
        '............kk..',
        '.....ppppp.PPP..',
        '...ppPPpppppPwP.',
        '..pPPpppppppPPP.',
        '..pPppppqppppp..',
        '..ppppppqpppp...',
        '...pppppqppp....',
        '....qqqqqqq.....',
        '....k..k..k.....',
        '...k..k..k......',
        E16,
        E16,
        E16,
    ],
    stalker0: [
        E16,
        '.......o........',
        '......ooo.......',
        '.....ooooo......',
        '....ooooooo.....',
        '...ooooooooo....',
        '..oowwooowwoo...',
        '..owwkkowwkko...',
        '..oowwooowwoo...',
        '..ooooooooooo...',
        '..ooooooooooo...',
        '..oYoooooooYo...',
        '..ooooooooooo...',
        '..oo.ooo.ooo....',
        '..o...o...o.....',
        E16,
    ],
    stalker1: [
        E16,
        '.......o........',
        '......ooo.......',
        '.....ooooo......',
        '....ooooooo.....',
        '...ooooooooo....',
        '..oowwooowwoo...',
        '..owwkkowwkko...',
        '..oowwooowwoo...',
        '..ooooooooooo...',
        '..ooooooooooo...',
        '..oYoooooooYo...',
        '..ooooooooooo...',
        '..ooo.ooo.oo....',
        '....o...o..o....',
        E16,
    ],
    borer0: [
        E16,
        E16,
        '....GGGGGGG.....',
        '...GgWggggGG....',
        '..GgWgggggkGG...',
        '..GggggGggggGWW.',
        '.GgggggGgggggWWW',
        '.GgggggGggggGWW.',
        '.GGgggggGgggG...',
        '..GGGgggGggGG...',
        '...GGGGGGGGG....',
        '...uu..uu.uu....',
        E16,
        E16,
        E16,
        E16,
    ],
    borer1: [
        E16,
        E16,
        '....GGGGGGG.....',
        '...GgWggggGG....',
        '..GgWgggggkGG...',
        '..GggggGggggGgW.',
        '.GgggggGgggggWgW',
        '.GgggggGggggGgW.',
        '.GGgggggGgggG...',
        '..GGGgggGggGG...',
        '...GGGGGGGGG....',
        '....uu..uu.uu...',
        E16,
        E16,
        E16,
        E16,
    ],
    scared0: [
        E16,
        '.....bbbbbb.....',
        '...bbbbbbbbbb...',
        '..bbbbbbbbbbbb..',
        '..bbbRRbbRRbbb..',
        '.bbbbRRbbRRbbbb.',
        '.bbbbbbbbbbbbbb.',
        '.bbbbbbbbbbbbbb.',
        '.bbRbbRbbRbbRbb.',
        '.bRbRRbRRbRRbRb.',
        '.bbbbbbbbbbbbbb.',
        '.bbbbbbbbbbbbbb.',
        '.bbbbbbbbbbbbbb.',
        '.bb.bbb..bbb.bb.',
        '.b...bb..bb...b.',
        E16,
    ],
    scared1: [
        E16,
        '.....bbbbbb.....',
        '...bbbbbbbbbb...',
        '..bbbbbbbbbbbb..',
        '..bbbRRbbRRbbb..',
        '.bbbbRRbbRRbbbb.',
        '.bbbbbbbbbbbbbb.',
        '.bbbbbbbbbbbbbb.',
        '.bbRbbRbbRbbRbb.',
        '.bRbRRbRRbRRbRb.',
        '.bbbbbbbbbbbbbb.',
        '.bbbbbbbbbbbbbb.',
        '.bbbbbbbbbbbbbb.',
        '.bbb.bb..bb.bbb.',
        '..b..b....b..b..',
        E16,
    ],
    eyes: [
        E16, E16, E16, E16,
        '...WWW....WWW...',
        '..WWWWW..WWWWW..',
        '..WWWkk..WWWkk..',
        '..WWWkk..WWWkk..',
        '..WWWWW..WWWWW..',
        '...WWW....WWW...',
        E16, E16, E16, E16, E16, E16,
    ],
    fire0: [
        E16, E16, E16,
        '......o.....o...',
        '...o.ooo..o.oo..',
        '..oooyoooooyooo.',
        '.ooyyyyooyyyyooo',
        'oyyyYYyyyyYYyyyo',
        'oyyYYYYyyYYYYyyo',
        '.ooyyyyooyyyyooo',
        '..oooyoooooyooo.',
        '...o.ooo..o.oo..',
        '......o.....o...',
        E16, E16, E16,
    ],

    // ---------------------------------------------------------- terrain props
    rock: [
        E16, E16,
        '.....GGGGGG.....',
        '...GGgggggggG...',
        '..GgWWggggggGG..',
        '.GgWWgggggggggG.',
        '.GgWgggggGggggG.',
        'GggggggggGgggggG',
        'GgggggggGggggggG',
        'GgggGGgggggggggG',
        'GggggGggggggggGG',
        '.GgggggggggggGG.',
        '.GGggggggggGGG..',
        '..GGGGGGGGGGG...',
        E16, E16,
    ],
    rockCrack: [
        E16, E16,
        '.....GGGGGG.....',
        '...GGgggkgggG...',
        '..GgWWgggkggGG..',
        '.GgWWggggkgggkG.',
        '.GgWgkggkGggkgG.',
        'GggggkggkGgkgggG',
        'GgggggkkGgkggggG',
        'GgggGGgkgggggggG',
        'GggggGggkgggggGG',
        '.GgggggggkgggGG.',
        '.GGggggggkgGGG..',
        '..GGGGGGGGGGG...',
        E16, E16,
    ],
    core0: [
        E16,
        '.......cc.......',
        '......cCCc......',
        '.....cCCccc.....',
        '....cCCcccct....',
        '...cCCccccctt...',
        '...cCcccccctt...',
        '..cCcccccccctt..',
        '..cccccccccttt..',
        '...ccccccctt....',
        '....cccccct.....',
        '.....ccctt......',
        '......ctt.......',
        '...GGGGGGGGGG...',
        '..GgggggggggggG.',
        '..GGGGGGGGGGGGG.',
    ],

    // ---------------------------------------------------------- tower heads
    headBlaster: [
        E16, E16, E16, E16,
        '....oooooo......',
        '...oyyyyyyo.....',
        '..oyYYyyyyyoWWWW',
        '..oyYyyyyyyogggg',
        '..oyyyyyyyyoWWWW',
        '..oyyyyyyyyogggg',
        '...oyyyyyyo.....',
        '....oooooo......',
        E16, E16, E16, E16,
    ],
    headFrost: [
        E16,
        '.......C........',
        '....C..c..C.....',
        '.....c.c.c......',
        '......ccc.......',
        '..C...cCc...C...',
        '...c..cwc..c....',
        '.Ccccccwcccccc..',
        '...c..cwc..c....',
        '..C...cCc...C...',
        '......ccc.......',
        '.....c.c.c......',
        '....C..c..C.....',
        '.......C........',
        E16, E16,
    ],
    headArc: [
        E16, E16,
        '......PPPP......',
        '.....PwwwwP.....',
        '....PwwPPwwP....',
        '....PwPppPwP....',
        '....PwPppPwP....',
        '....PwwPPwwP....',
        '.....PwwwwP.....',
        '......PPPP......',
        '.......pp.......',
        '......pqqp......',
        '.....pqqqqp.....',
        '....qqqqqqqq....',
        E16, E16,
    ],
    headBoomer: [
        E16, E16, E16, E16,
        '....GGGG........',
        '...GrrrrG.......',
        '..GrRRrrrGGGGGG.',
        '..GrRrrrrrgggggG',
        '..GrrrrrrrgggggG',
        '..GrrrrrrGGGGGG.',
        '...GrrrrG.......',
        '....GGGG........',
        E16, E16, E16, E16,
    ],

    // ---------------------------------------------------------- bonus veggies
    carrot: [
        E16,
        '...........e.e..',
        '..........eEe...',
        '.........ooee...',
        '........oooo....',
        '.......oYooo....',
        '......oYooo.....',
        '.....ooooo......',
        '....oOooo.......',
        '...ooooo........',
        '...oOoo.........',
        '..ooo...........',
        '..oo............',
        '.o..............',
        E16, E16,
    ],
    turnip: [
        E16,
        '.......e.e......',
        '......eEeEe.....',
        '.......eee......',
        '.....wwwwww.....',
        '....wwwwwwww....',
        '...wwwWwwwwww...',
        '...wwWwwwwwww...',
        '...mmmmmmmmmm...',
        '...mmmmmmmmmm...',
        '....mmmmmmmm....',
        '.....mmmmmm.....',
        '.......mm.......',
        '.......m........',
        E16, E16,
    ],
    mushroom: [
        E16, E16,
        '.....rrrrrr.....',
        '...rrwwrrrrrr...',
        '..rrwwwrrrwwrr..',
        '.rrrwwrrrrwwwrr.',
        '.rrrrrrrrrrrrrr.',
        '.rrwwrrrrrrrwrr.',
        '..rrrrrrrrrrrr..',
        '....wwwwwwww....',
        '.....wwwwww.....',
        '.....wWwwww.....',
        '.....wWwwww.....',
        '......wwww......',
        E16, E16,
    ],
    eggplant: [
        E16,
        '.......e........',
        '......eee.......',
        '.....eEeee......',
        '......ppp.......',
        '.....ppppp......',
        '....pPpppp......',
        '....pPppppp.....',
        '...pPpppppp.....',
        '...pppppppp.....',
        '...ppppppppp....',
        '....ppppppp.....',
        '.....ppppp......',
        E16, E16, E16,
    ],

    // ---------------------------------------------------------- small bits
    gem: [
        '...CC...',
        '..CwCC..',
        '.CwCccC.',
        'CCccccCt',
        'tCcccCtt',
        '.tCcCtt.',
        '..tCtt..',
        '...tt...',
    ],
    ore: [
        '..w...',
        '.wCc..',
        'wCcct.',
        '.cct..',
        '..t...',
        '......',
    ],
    flower: [
        '...ww...',
        '..wyyw..',
        '...ww...',
        '...e....',
        '..ee.e..',
        '...eee..',
        '...e....',
        '...e....',
    ],
    heart: [
        '.rr.rr.',
        'rRrrrrr',
        'rRrrrrr',
        'rrrrrrr',
        '.rrrrr.',
        '..rrr..',
        '...r...',
    ],
    coin: [
        '..yyy..',
        '.yYyyy.',
        'yYyoyyo',
        'yYyoyyo',
        'yyyoyyo',
        '.yyyyo.',
        '..ooo..',
    ],
    coreIcon: [
        '...c...',
        '..cCc..',
        '.cCcct.',
        'cCccctt',
        '.ccctt.',
        '..ctt..',
        '...t...',
    ],
    harpoon: [
        '........',
        '..W.....',
        '..WWW...',
        'WWWWWWW.',
        'WWWWWWW.',
        '..WWW...',
        '..W.....',
        '........',
    ],
    crown: [
        '...y....y....y..',
        '...yy..yyy..yy..',
        '...yyyyyyyyyyy..',
        '...yrYyyByyYry..',
        '...yyyyyyyyyyy..',
    ],
};

// Sprites made from other sprites: palette swaps and flips.
export const DERIVED = {
    scaredW0: { from: 'scared0', swap: { b: 'W', R: 'r' } },
    scaredW1: { from: 'scared1', swap: { b: 'W', R: 'r' } },
    fire1:    { from: 'fire0', flipX: true },
    core1:    { from: 'core0', swap: { c: 'C', t: 'c', C: 'w' } },
};

// Earthier greys for the rocks, so they read as stone rather than metal.
export const SPRITE_PAL = {
    // Greyscale so the renderer's colour tint cycles it through clean hues.
    gem:       { C: '#ffffff', c: '#d8d8d8', t: '#8c8c8c', w: '#ffffff' },
    rock:      { G: '#4a3a34', g: '#9a8676', W: '#e0d2c0', k: '#2a1c18' },
    rockCrack: { G: '#4a3a34', g: '#9a8676', W: '#e0d2c0', k: '#2a1c18' },
};
