// Quick persistence check: play, die, respawn, save, reload, continue. (dev helper)
import { chromium } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const HERE = path.dirname(fileURLToPath(import.meta.url));
const PKG = [path.join(HERE, 'package'), path.join(HERE, '../../dev/package')].find((p) => fs.existsSync(p));
const BASE = process.env.BASE ?? 'http://127.0.0.1:8061';
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--no-sandbox'] });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 760 } });
const page = await ctx.newPage();
await page.route('https://unpkg.com/**', (r) => { const f = path.join(PKG, new URL(r.request().url()).pathname.replace(/^\/three@0\.165\.0\//, '')); r.fulfill({ status: 200, contentType: 'application/javascript', body: fs.readFileSync(f) }); });
await page.route('https://fonts.googleapis.com/**', (r) => r.fulfill({ status: 200, contentType: 'text/css', body: '' }));
const errors = [];
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
page.on('pageerror', (e) => errors.push(e.message));
const ev = (js) => page.evaluate(`(() => { const S = window.__sw; ${js} })()`);
await page.goto(`${BASE}/game-061/index.html?debug=1`);
await page.waitForFunction(() => window.__sw?.world);
await ev(`S.app.newGame('PERSIST-1','Kestrel'); S.app.undock(); S.give('ferrite', 12); S.credits(1000);`);
await page.waitForTimeout(500);
await ev(`S.world.damagePlayer(9999, true);`);
await page.waitForFunction(() => window.__sw.menus.kind === 'death', null, { timeout: 60000 });
console.log('death menu shown; cargo before respawn', await ev(`return JSON.stringify(S.game.s.cargo)`));
await page.click('text=WAKE UP AT HEARTH');
await page.waitForFunction(() => window.__sw.mode === 'docked');
console.log('respawned docked at', await ev(`return S.game.s.location.docked`), 'credits', await ev(`return S.game.s.credits`));
await ev(`S.app.quitToTitle()`);
await page.reload();
await page.waitForFunction(() => window.__sw?.world);
const cont = await page.locator('text=CONTINUE').count();
console.log('continue button', cont);
await page.click('text=CONTINUE');
await page.waitForFunction(() => window.__sw.mode === 'docked' || window.__sw.mode === 'flight');
console.log('continued:', await ev(`return [S.game.s.seed, S.game.s.ship.name, S.game.s.stats.deaths, S.mode]`));
console.log(errors.length ? errors.join('\n') : 'no errors');
await browser.close();
