/**
 * worlds.js — the ten realms. Pure data shared by the simulation (names,
 * bestiary archetypes, place-name words), the view (palettes, props, weather)
 * and the audio (mode, tempo, root).
 *
 * Colours are 0xRRGGBB. `arch` lists the monster archetypes that live there.
 */

export const WORLD_DEFS = [
    {
        key: 'emberfall', name: 'Emberfall Marches', short: 'Emberfall',
        warden: 'The Scarecrow Baron', boss: 'baron', crown: 'crownAsh',
        sky: [0x1a0b0a, 0x5a1e10, 0xe0622a], sun: 0xff8a3a, sunPos: [-0.35, 0.16], fog: 0x3a1a12, fogDensity: 0.022,
        ground: [0x2a1a12, 0x4a2a16], hills: [0x1a0e0c, 0x2e1610, 0x4a2012], accent: 0xff7a2a, rim: 0xffb070,
        weather: 'embers', props: ['wheat', 'post', 'deadTree', 'cottage'], stars: 0.1, clouds: 0.8, aurora: 0,
        arch: ['blob', 'beast', 'knight', 'flyer', 'bloom', 'wraith'],
        pre: ['Cinder', 'Ash', 'Smoul', 'Char', 'Soot', 'Brand', 'Kiln', 'Scorch'], post: ['maw', 'tooth', 'lurk', 'crow', 'hide', 'gnaw', 'wick', 'fang'],
        placeAdj: ['Burning', 'Weeping', 'Blackened', 'Smouldering', 'Hollow', 'Last'], placeNoun: ['Mile', 'Furrow', 'Hollow', 'Mill', 'Crossing', 'Barrow', 'Fields', 'Chapel'],
        music: { root: 50, mode: 'dorian', bpm: 92 },
    },
    {
        key: 'cathedral', name: 'The Drowned Cathedral', short: 'Drowned Cathedral',
        warden: 'The Tidebound Abbess', boss: 'abbess', crown: 'crownTides',
        sky: [0x020c16, 0x06324a, 0x1a8a9a], sun: 0x7affe8, sunPos: [0.3, 0.3], fog: 0x042a36, fogDensity: 0.03,
        ground: [0x0a2a30, 0x12404a], hills: [0x031418, 0x062428, 0x0c3a40], accent: 0x40ffd8, rim: 0x80fff0,
        weather: 'bubbles', props: ['pillar', 'arch', 'kelp', 'candle'], stars: 0, clouds: 0.3, aurora: 0.4,
        arch: ['serpent', 'wraith', 'eye', 'blob', 'knight', 'bloom'],
        pre: ['Brine', 'Silt', 'Drown', 'Vesper', 'Kelp', 'Tide', 'Hymn', 'Pale'], post: ['choir', 'fin', 'gill', 'maw', 'wight', 'coil', 'lamp', 'shroud'],
        placeAdj: ['Sunken', 'Silent', 'Flooded', 'Choral', 'Pale', 'Drowned'], placeNoun: ['Nave', 'Cloister', 'Font', 'Reliquary', 'Aisle', 'Bell-tower', 'Crypt', 'Apse'],
        music: { root: 45, mode: 'aeolian', bpm: 80 },
    },
    {
        key: 'thornwild', name: 'Thornwild', short: 'Thornwild',
        warden: 'The Briar Queen', boss: 'briar', crown: 'crownBriars',
        sky: [0x06120a, 0x12361a, 0x7ac86a], sun: 0xd0ff8a, sunPos: [0.1, 0.42], fog: 0x0e2a14, fogDensity: 0.028,
        ground: [0x14240e, 0x243a14], hills: [0x08140a, 0x0e2210, 0x163418], accent: 0xb0ff60, rim: 0xe0ffa0,
        weather: 'spores', props: ['tree', 'mushroom', 'thorn', 'stone'], stars: 0.2, clouds: 0.4, aurora: 0,
        arch: ['bloom', 'beast', 'flyer', 'golem', 'wraith', 'serpent'],
        pre: ['Thorn', 'Briar', 'Moss', 'Bramble', 'Fey', 'Root', 'Hawthorn', 'Gall'], post: ['wick', 'thorn', 'sprite', 'bark', 'bloom', 'stag', 'snare', 'weald'],
        placeAdj: ['Tangled', 'Green', 'Dreaming', 'Thorned', 'Sleeping', 'Old'], placeNoun: ['Glade', 'Hedge', 'Court', 'Ring', 'Bower', 'Wood', 'Path', 'Well'],
        music: { root: 52, mode: 'lydian', bpm: 96 },
    },
    {
        key: 'dunes', name: 'Glasswind Dunes', short: 'Glasswind',
        warden: 'The Mirage Sultan', boss: 'sultan', crown: 'crownMirage',
        sky: [0x2a1a3a, 0xc0604a, 0xffd08a], sun: 0xfff0c0, sunPos: [-0.25, 0.22], fog: 0x8a5a4a, fogDensity: 0.016,
        ground: [0xb8864a, 0xe0b070], hills: [0x6a3a3a, 0x9a5a4a, 0xc88a5a], accent: 0x60e0ff, rim: 0xffe0a0,
        weather: 'sand', props: ['crystal', 'dune', 'obelisk', 'bones'], stars: 0.15, clouds: 0.2, aurora: 0, twinSun: true,
        arch: ['golem', 'serpent', 'eye', 'construct', 'beast', 'wraith'],
        pre: ['Glass', 'Dune', 'Sirocco', 'Mirage', 'Sand', 'Shard', 'Sun', 'Salt'], post: ['strider', 'jinn', 'scarab', 'wyrm', 'sphinx', 'glint', 'veil', 'husk'],
        placeAdj: ['Shimmering', 'Endless', 'Glass', 'Sun-bleached', 'Singing', 'Lost'], placeNoun: ['Dune', 'Oasis', 'Caravan', 'Bazaar', 'Tomb', 'Well', 'Mirror', 'Road'],
        music: { root: 50, mode: 'phrygianDom', bpm: 100 },
    },
    {
        key: 'frost', name: 'Frostmourn Peaks', short: 'Frostmourn',
        warden: 'The Rime Colossus', boss: 'colossus', crown: 'crownRime',
        sky: [0x02060e, 0x0a1a3a, 0x4a7aaa], sun: 0xd8f0ff, sunPos: [0.35, 0.34], fog: 0x1a2a40, fogDensity: 0.024,
        ground: [0xc8d8e8, 0xe8f4ff], hills: [0x0e1a2a, 0x2a3e5a, 0x7a9abe], accent: 0x8ae0ff, rim: 0xd0f4ff,
        weather: 'snow', props: ['iceSpike', 'pine', 'rock', 'cairn'], stars: 0.9, clouds: 0.2, aurora: 1,
        arch: ['golem', 'beast', 'wraith', 'construct', 'flyer', 'knight'],
        pre: ['Rime', 'Frost', 'Hoar', 'Sleet', 'Glacier', 'Winter', 'Ice', 'Numb'], post: ['fang', 'howl', 'shard', 'giant', 'wight', 'tusk', 'mourn', 'drift'],
        placeAdj: ['Frozen', 'White', 'Howling', 'Bitter', 'Silent', 'Starlit'], placeNoun: ['Pass', 'Col', 'Cairn', 'Glacier', 'Summit', 'Cave', 'Ridge', 'Lake'],
        music: { root: 47, mode: 'aeolian', bpm: 84 },
    },
    {
        key: 'deep', name: 'The Gilded Deep', short: 'Gilded Deep',
        warden: 'Mammon, the Coin-Eater', boss: 'mammon', crown: 'crownMammon',
        sky: [0x0a0402, 0x2a1004, 0x8a3a08], sun: 0xffc040, sunPos: [0.0, -0.1], fog: 0x2a1204, fogDensity: 0.03,
        ground: [0x2a1a10, 0x3a2410], hills: [0x120804, 0x201008, 0x3a1a08], accent: 0xffc030, rim: 0xffd880,
        weather: 'gold', props: ['stalagmite', 'goldPile', 'forge', 'column'], stars: 0, clouds: 0, aurora: 0, lava: true,
        arch: ['construct', 'golem', 'beast', 'blob', 'knight', 'eye'],
        pre: ['Gild', 'Coin', 'Forge', 'Ingot', 'Mint', 'Hoard', 'Brass', 'Slag'], post: ['grub', 'hoarder', 'golem', 'miser', 'hammer', 'drake', 'purse', 'smith'],
        placeAdj: ['Golden', 'Molten', 'Deep', 'Glittering', 'Forsaken', 'Greedy'], placeNoun: ['Vault', 'Mine', 'Forge', 'Hall', 'Seam', 'Treasury', 'Shaft', 'Mint'],
        music: { root: 43, mode: 'harmonicMinor', bpm: 88 },
    },
    {
        key: 'aerie', name: 'Skyreach Aerie', short: 'Skyreach',
        warden: 'The Storm Roc', boss: 'roc', crown: 'crownStorm',
        sky: [0x1a2a5a, 0x5a8ad0, 0xd8ecff], sun: 0xfff8e0, sunPos: [-0.3, 0.4], fog: 0x9ab8e0, fogDensity: 0.012,
        ground: [0x6a8a5a, 0x8aaa6a], hills: [0x4a6a9a, 0x7a9ac8, 0xb0c8e8], accent: 0xffe060, rim: 0xffffff,
        weather: 'feathers', props: ['isle', 'cloud', 'windmill', 'banner'], stars: 0, clouds: 1, aurora: 0,
        arch: ['flyer', 'construct', 'wraith', 'eye', 'serpent', 'knight'],
        pre: ['Gale', 'Storm', 'Cloud', 'Zephyr', 'Thunder', 'Sky', 'Talon', 'Squall'], post: ['wing', 'talon', 'harpy', 'spark', 'drake', 'kite', 'rider', 'eye'],
        placeAdj: ['High', 'Windswept', 'Floating', 'Thundering', 'Bright', 'Broken'], placeNoun: ['Isle', 'Eyrie', 'Bridge', 'Spire', 'Nest', 'Landing', 'Mast', 'Gate'],
        music: { root: 55, mode: 'mixolydian', bpm: 108 },
    },
    {
        key: 'carnival', name: 'The Umbral Carnival', short: 'Umbral Carnival',
        warden: 'The Harlequin', boss: 'harlequin', crown: 'crownJoker',
        sky: [0x08020e, 0x2a0a3a, 0x9a2a8a], sun: 0xff60e0, sunPos: [0.25, 0.3], fog: 0x1a0626, fogDensity: 0.026,
        ground: [0x1a0a22, 0x2a1234], hills: [0x0c0412, 0x1a0824, 0x2e0e3a], accent: 0xff40c0, rim: 0x60ffff,
        weather: 'confetti', props: ['tent', 'lantern', 'carousel', 'balloon'], stars: 0.6, clouds: 0.3, aurora: 0,
        arch: ['jester', 'construct', 'eye', 'blob', 'wraith', 'knight'],
        pre: ['Mum', 'Motley', 'Grin', 'Pierrot', 'Masque', 'Jest', 'Rictus', 'Puppet'], post: ['bell', 'grin', 'fool', 'mime', 'strings', 'clown', 'mask', 'tumbler'],
        placeAdj: ['Grinning', 'Midnight', 'Gilded', 'Laughing', 'Crooked', 'Mirrored'], placeNoun: ['Tent', 'Ring', 'Midway', 'Parade', 'Carousel', 'Stage', 'Maze', 'Booth'],
        music: { root: 48, mode: 'harmonicMinor', bpm: 112 },
    },
    {
        key: 'starless', name: 'The Starless Sea', short: 'Starless Sea',
        warden: 'The Leviathan of Nothing', boss: 'leviathan', crown: 'crownDeep',
        sky: [0x000002, 0x0a0420, 0x3a1a6a], sun: 0xb090ff, sunPos: [-0.1, 0.3], fog: 0x06021a, fogDensity: 0.02,
        ground: [0x06040e, 0x0e0820], hills: [0x020108, 0x06041a, 0x120a30], accent: 0xa080ff, rim: 0xd0c0ff,
        weather: 'stardust', props: ['monolith', 'shell', 'wreck', 'cardDrift'], stars: 1, clouds: 0, aurora: 0.6, nebula: true,
        arch: ['eye', 'serpent', 'wraith', 'blob', 'construct', 'bloom'],
        pre: ['Void', 'Null', 'Umbra', 'Abyss', 'Hollow', 'Nadir', 'Lethe', 'Eclipse'], post: ['maw', 'gaze', 'drifter', 'wyrm', 'shade', 'coil', 'echo', 'spawn'],
        placeAdj: ['Starless', 'Forgotten', 'Endless', 'Unmade', 'Dim', 'Final'], placeNoun: ['Shore', 'Tide', 'Reef', 'Deep', 'Wreck', 'Strand', 'Drift', 'Gulf'],
        music: { root: 44, mode: 'locrianish', bpm: 76 },
    },
    {
        key: 'throne', name: 'The Hollow Throne', short: 'Hollow Throne',
        warden: 'The Hollow King', boss: 'king', crown: null,
        sky: [0x050302, 0x2a1810, 0x9a5a3a], sun: 0xffe0a0, sunPos: [0.0, 0.28], fog: 0x201410, fogDensity: 0.022,
        ground: [0x2a2420, 0x3a322a], hills: [0x0c0a08, 0x1a1410, 0x2e2218], accent: 0xffd070, rim: 0xffe8c0,
        weather: 'ash', props: ['throneSpire', 'statue', 'brazier', 'banner'], stars: 0.3, clouds: 0.6, aurora: 0,
        arch: ['knight', 'wraith', 'golem', 'construct', 'flyer', 'jester'],
        pre: ['Hollow', 'Crown', 'Ashen', 'Throne', 'Regal', 'Last', 'Grey', 'Ember'], post: ['guard', 'herald', 'lord', 'warden', 'knight', 'shade', 'sworn', 'blade'],
        placeAdj: ['Hollow', 'Ashen', 'Royal', 'Final', 'Crowned', 'Broken'], placeNoun: ['Gate', 'Stair', 'Hall', 'Court', 'Gallery', 'Keep', 'Bridge', 'Throne-road'],
        music: { root: 50, mode: 'aeolian', bpm: 90 },
    },
];

/** Scale factors by world index 0-9, tuned with dev/simtest.mjs. */
export function hpScale(w) { return 1 + 0.55 * w + 0.09 * w * w; }
export function dmgScale(w) { return 1 + 0.22 * w + 0.02 * w * w; }
